language: android

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28

script: ./gradlew build

